version: '3.2'
services:
  db:
    image: library/postgres:13.1
    container_name: event-bridge-postgres
    environment:
      POSTGRES_USER: dinosaur
      POSTGRES_PASSWORD: dinosaur
      POSTGRES_DB: dinosaur
    ports:
      - "5432:5432"


  keycloak:
    image: jboss/keycloak:10.0.1
    command: "-b 0.0.0.0 -Djboss.socket.binding.port-offset=100 -Dkeycloak.import=/keycloak-config/dinosaur-fm-realm-sample.json"
    container_name: dinosaur-keycloak
    ports:
      - "8180:8180"
    volumes:
      # Adding the "z" flag to get SELinux configured automatically
      - ./keycloak-config:/keycloak-config:z
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "123"